name: breez_sdk
description: A new flutter plugin project.
version: 0.0.4
publish_to: none

environment:
  sdk: ">=2.19.4 <3.0.0"
  flutter: ">=3.7.7"

dependencies:
  flutter:
    sdk: flutter
  fimber: ^0.6.6
  ### flutter_rust_bridge_codegen dependencies
  ffi: ^2.0.1
  flutter_rust_bridge: 1.70.0
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  ###
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  # The following dependencies are required by flutter_rust_bridge_codegen to
  # be defined under dev_dependencies to generate Dart files
  build_runner: ^2.3.3
  ffigen: ^7.2.9

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.breez.breez_sdk
        pluginClass: BreezSDKPlugin
      ios:
        pluginClass: BreezSDKPlugin